name: 02 Build with BuildKit Cache

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      # New step
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: justsanti/docker-ci-automation:02
          # New cache
          cache-from: type=gha
          cache-to: type=gha, mode=max
